# Reuse the upstream CPU routines without editing or maintaining a fork of the
# submodule. Only rename the private entry points and initialize SV eta_p.
set(FK_REFERENCE_SOURCE "${SPECFEM_DIR}/src/specfem3D/couple_with_injection.f90")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${FK_REFERENCE_SOURCE}")
file(READ "${FK_REFERENCE_SOURCE}" FK_REFERENCE_TEXT)
string(FIND "${FK_REFERENCE_TEXT}" "  subroutine FK3D(" FK_REFERENCE_START)
string(FIND "${FK_REFERENCE_TEXT}" "  end subroutine FK\n" FK_REFERENCE_END)
if(FK_REFERENCE_START LESS 0 OR FK_REFERENCE_END LESS FK_REFERENCE_START)
  message(FATAL_ERROR "Cannot locate upstream FK routines for the FWAT reference")
endif()
math(EXPR FK_REFERENCE_LENGTH "${FK_REFERENCE_END} - ${FK_REFERENCE_START} + 20")
string(SUBSTRING "${FK_REFERENCE_TEXT}" ${FK_REFERENCE_START} ${FK_REFERENCE_LENGTH} FK_REFERENCE_TEXT)
string(REPLACE "FK3D" "FK3D_fwat" FK_REFERENCE_TEXT "${FK_REFERENCE_TEXT}")
string(REPLACE "subroutine FK(" "subroutine FK_fwat(" FK_REFERENCE_TEXT "${FK_REFERENCE_TEXT}")
string(REPLACE "subroutine FK\n" "subroutine FK_fwat\n" FK_REFERENCE_TEXT "${FK_REFERENCE_TEXT}")
string(REPLACE "call FK(" "call FK_fwat(" FK_REFERENCE_TEXT "${FK_REFERENCE_TEXT}")
set(FK_SV_LINE "eta_s = sqrt(1.0/vs(nlayer)**2 - ray_p**2)")
string(FIND "${FK_REFERENCE_TEXT}" "${FK_SV_LINE}" FK_SV_POSITION)
if(FK_SV_POSITION LESS 0)
  message(FATAL_ERROR "Upstream FK SV branch changed; review the FWAT eta_p fix")
endif()
string(REPLACE "${FK_SV_LINE}" "${FK_SV_LINE}\n    eta_p = eta_s" FK_REFERENCE_TEXT "${FK_REFERENCE_TEXT}")
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/fk_reference.f90"
  CONTENT "! Generated from SPECFEM (GPL-3.0-or-later); SV delay fix only.\n${FK_REFERENCE_TEXT}\n" @ONLY)
list(APPEND FK_SOURCES "${CMAKE_CURRENT_BINARY_DIR}/fk_reference.f90")
